server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Mos278/ConfigServer
    bus:
      enabled: true
      refresh:
        enabled: true
      env:
        enabled: true
      trace:
        enabled: true
    stream:
      kafka:
        binder:
          autoAddPartitions: true
          brokers: localhost:9092
          zkNodes: localhost:2181



#ex-profile:
#  value1: ${value1}

endpoints:
    spring:
      cloud:
        bus:
          refresh:
            enabled: true
        env:
          enabled: true



management:
  endpoints:
    web:
      exposure:
        include: "*"






#            vault:
#              kv:
#                enabled: true
#                application-name: vault
#              authentication: TOKEN
#              token: hvs.OnVHYGu1mPHz3wJ4J9qCFbfQ #Token User
#              scheme: http
#              host: 127.0.0.1
#              port: 8200
#              connection-timeout: 5000
#              read-timeout: 15000