server:
  port: 8081
spring:
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
      env:
        enabled: true
      trace:
        enabled: true
    stream:
      kafka:
        binder:
          autoAddPartitions: true
          brokers: localhost:9092
          zkNodes: localhost:2181
    config:
      url: localhost:8888
      override-none: true
      import-check:
        enabled: false
    vault:
      kv:
        enabled: true
        application-name: vault
      authentication: TOKEN
      token:  #Token User
      scheme: http
      host: 127.0.0.1
      port: 8200
      connection-timeout: 5000
      read-timeout: 15000
  config:
    import: vault://secret/uchoose/app-config/app,
      vault://secret/uchoose/app-config/app/dev,
      vault://secret/uchoose/app-config/app/remote

management:
  endpoints:
    web:
      exposure:
        include: "*"


endpoints:
  spring:
    cloud:
      bus:
        refresh:
          enabled: true
      env:
        enabled: true

ex-profile:
  value1: ${value1}
  value2: ${value2}
  value3: ${value3}

